language: cpp
dist: bionic
os:
  - linux
sudo: require
install:
  - sudo apt-get install nasm
  - sudo apt-get install xorg-dev libglu1-mesa-dev mesa-common-dev
services:
  - xvfb
branches:
  only:
    - master
before_script:
  - mkdir build
  - cd build
  - cmake .. -DDJV_THIRD_PARTY=TRUE
script: make && make test

