language: cpp
dist: bionic
os:
  - linux
sudo: require
install:
  - sudo apt-get install libgl1-mesa-dri
services:
  - xvfb
branches:
  only:
    - master
before_script:
  - mkdir build
  - cd build
  - cmake .. -DDJV_THIRD_PARTY=TRUE
script: make && make test

