trigger:
- master

jobs:
- job: Linux
  pool:
    vmImage: 'ubuntu-18.04'
  container:
    image: aswftesting/ci-base:2020.1
  steps:
  - script: |
      mkdir build
      cd build
      # ASWF container doesn't have lcov or nasm
      sudo yum install -y epel-release
      sudo yum install -y lcov nasm
      # This seems to be sufficient to make OpenGL / GLX software rasterization work
      sudo yum install -y mesa-dri-drivers
      # OTIO build needs a git user
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      export DJV_BUILD=$PWD
      export PATH=$PATH:$DJV_BUILD/DJV-install-Debug/bin
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DJV_BUILD/DJV-install-Debug/lib
      export PYTHONPATH=$DJV_BUILD/DJV-install-Debug/lib:$PYTHONPATH
      echo "Building third party dependencies..."
      mkdir DJV-third-party-Debug
      cd DJV-third-party-Debug
      cmake ../../third-party -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_OPENGL_ES2=TRUE
      cmake --build .
      cmake --build . --target install
      cd ..
      echo "Building DJV..."
      mkdir DJV-Debug
      cd DJV-Debug
      cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Debug -DCMAKE_PREFIX_PATH=$DJV_BUILD/DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_BUILD_TINY=TRUE -DDJV_GCOV=TRUE -DDJV_OPENGL_ES2=TRUE
      # ASWF ci-base image already contains the SonarCloud tools in /usr/bin
      build-wrapper-linux-x86-64 --out-dir ../bw-output cmake --build . -j 4
      # Need to request 24bit visual to get OpenGL
      xvfb-run --server-args "-screen 0 640x480x24" cmake --build . --target test
      cat Testing/Temporary/LastTest.log
      sh ../../etc/Util/gcov.sh ../..
      #- cppcheck --enable=all --xml-version=2 -I${PWD}/lib -UDJV_ASSERT -UDJV_ENDIAN_MSB -UDJV_MMAP -UDJV_OPENGL_ES2 -UDJV_PLATFORM_WINDOWS -UGLM_PRECISION_LOWP_FLOAT -UGLM_PRECISION_LOWP_INT -UGLM_PRECISION_MEDIUMP_FLOAT -UGLM_PRECISION_MEDIUMP_INT -UDJV_OPENGL_PBO -Umax -Umin lib bin examples 2> report.xml
      cd ../..

- job: Linux_Packaging
  pool:
    vmImage: 'ubuntu-latest'
  steps:
  - script: |
      mkdir build
      cd build
      sudo apt-get install libgl1-mesa-dev xorg-dev libasound2-dev
      # OTIO build needs a git user
      git config --global user.email "you@example.com"
      git config --global user.name "Your Name"
      export DJV_BUILD=$PWD
      export PATH=$PATH:$DJV_BUILD/DJV-install-Release/bin
      export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DJV_BUILD/DJV-install-Release/lib
      export PYTHONPATH=$DJV_BUILD/DJV-install-Release/lib:$PYTHONPATH
      echo "Building third party dependencies..."
      mkdir DJV-third-party-Release
      cd DJV-third-party-Release
      cmake ../../third-party -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Release
      cmake --build .
      cmake --build . --target install
      cd ..
      echo "Building DJV..."
      mkdir DJV-Release
      cd DJV-Release
      cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Release -DCMAKE_PREFIX_PATH=$DJV_BUILD/DJV-install-Release
      cmake --build . -j 4
      echo "Packaging DJV..."
      sudo apt-get install rpm-build
      cmake ../.. -DCPACK_GENERATOR=RPM -DCPACK_PACKAGING_INSTALL_PREFIX=/usr/local/DJV2 -DDJV_THIRD_PARTY=TRUE
      cmake --build . -j 4
      cmake --build . --target package
      cmake ../.. -DCPACK_GENERATOR=DEB -DCPACK_PACKAGING_INSTALL_PREFIX=/usr/local/DJV2 -DDJV_THIRD_PARTY=TRUE
      cmake --build . -j 4
      cmake --build . --target package
      cmake ../.. -DCPACK_GENERATOR=TGZ  -DCPACK_PACKAGING_INSTALL_PREFIX= -DDJV_THIRD_PARTY=TRUE
      cmake --build . -j 4
      cmake --build . --target package
      cd ../..

- job: Windows
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: |
      mkdir build
      cd build
      set DJV_BUILD=%CD%
      set PATH=%DJV_BUILD%\DJV-install-Debug\bin;%PATH%
      set PYTHONPATH=%DJV_BUILD%\DJV-install-Debug\lib;%PYTHONPATH%
      echo "Building third party dependencies..."
      mkdir DJV-third-party-Debug
      cd DJV-third-party-Debug
      cmake ..\..\third-party -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%DJV_BUILD%/DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_OPENGL_ES2=TRUE
      cmake --build . -j 4
      cmake --build . --target install
      cd ..
      echo "Building DJV..."
      mkdir DJV-Debug
      cd DJV-Debug
      cmake ..\.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=%DJV_BUILD%/DJV-install-Debug -DCMAKE_PREFIX_PATH=%DJV_BUILD%/DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_BUILD_TINY=TRUE -DDJV_OPENGL_ES2=TRUE
      cmake --build . -j 4
      rem Fails with:
      rem MSBUILD : error MSB1009: Project file does not exist.
      rem cmake --build . --target test
      rem type Testing/Temporary/LastTest.log
      cd ..\..

- job: Windows_Packaging
  pool:
    vmImage: 'windows-latest'
  steps:
  - powershell: |
      $ErrorActionPreference = "Stop"
      $url = "https://www.nasm.us/pub/nasm/releasebuilds/2.14.02/win64/nasm-2.14.02-win64.zip"
      Invoke-WebRequest -Uri $url -OutFile nasm-2.14.02-win64.zip -UserAgent "NativeClient"
      Expand-Archive nasm-2.14.02-win64.zip -DestinationPath .
    displayName: 'Download NASM'
  - script: |
      set PATH=%CD%\nasm-2.14.02;%PATH%
      echo %PATH%
      dir %CD%\nasm-2.14.02
      mkdir build
      cd build
      set DJV_BUILD=%CD%
      set PATH=%DJV_BUILD%\DJV-install-Release\bin;%DJV_DIR%\nasm-2.14.02;%PATH%
      set PYTHONPATH=%DJV_BUILD%\DJV-install-Release\lib;%PYTHONPATH%
      echo "Building third party dependencies..."
      mkdir DJV-third-party-Release
      cd DJV-third-party-Release
      cmake ..\..\third-party -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%DJV_BUILD%/DJV-install-Release
      cmake --build .
      cmake --build . --target install
      cd ..
      echo "Building DJV..."
      mkdir DJV-Release
      cd DJV-Release
      cmake ..\.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%DJV_BUILD%/DJV-install-Release -DCMAKE_PREFIX_PATH=%DJV_BUILD%/DJV-install-Release
      cmake --build .
      cmake ..\.. -DDJV_THIRD_PARTY=TRUE
      cmake --build .
      cmake --build . --target package
      cd ..\..

- job: macOS
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      mkdir build
      cd build
      export DJV_BUILD=$PWD
      export PATH=$PATH:$DJV_BUILD/DJV-install-Debug/bin
      export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$DJV_BUILD/DJV-install-Debug/lib
      export PYTHONPATH=$DJV_BUILD/DJV-install-Debug/lib:$PYTHONPATH
      echo "Building third party dependencies..."
      mkdir DJV-third-party-Debug
      cd DJV-third-party-Debug
      cmake ../../third-party -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_OPENGL_ES2=TRUE -DCMAKE_FIND_FRAMEWORK="LAST"
      cmake --build . -j 4
      cmake --build . --target install
      cd ..
      echo "Building DJV..."
      mkdir DJV-Debug
      cd DJV-Debug
      cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Debug -DCMAKE_PREFIX_PATH=$DJV_BUILD/DJV-install-Debug -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_BUILD_TINY=TRUE -DDJV_OPENGL_ES2=TRUE -DCMAKE_FIND_FRAMEWORK="LAST"
      cmake --build . -j 4
      # Fails with:
      # Unable to create basic Accelerated OpenGL renderer.
      # Core Image is now using the software OpenGL renderer. This will be slow.
      # ERROR: Cannot create GLFW window.
      #cmake --build . --target test
      #cat Testing/Temporary/LastTest.log
      cd ../..

- job: macOS_Packaging
  pool:
    vmImage: 'macOS-latest'
  steps:
  - script: |
      mkdir build
      cd build
      export DJV_BUILD=$PWD
      export PATH=$PATH:$DJV_BUILD/DJV-install-Release/bin
      export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$DJV_BUILD/DJV-install-Release/lib
      export PYTHONPATH=$DJV_BUILD/DJV-install-Release/lib:$PYTHONPATH
      echo "Building third party dependencies..."
      mkdir DJV-third-party-Release
      cd DJV-third-party-Release
      cmake ../../third-party -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Release -DCMAKE_FIND_FRAMEWORK="LAST"
      cmake --build . -j 4
      cmake --build . --target install
      cd ..
      echo "Building DJV..."
      mkdir DJV-Release
      cd DJV-Release
      cmake ../.. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/DJV-install-Release -DCMAKE_PREFIX_PATH=$DJV_BUILD/DJV-install-Release -DCMAKE_FIND_FRAMEWORK="LAST"
      cmake --build . -j 4
      echo "Packaging DJV..."
      cmake ../.. -DDJV_THIRD_PARTY=TRUE
      cmake --build . -j 4
      cmake --build . --target package
      cd ../..

