name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Update
      run: sudo apt-get update

    - name: Install lcov
      run: sudo apt-get install lcov

    - name: Install OpenGL dev
      run: sudo apt-get install xorg-dev libglu1-mesa-dev mesa-common-dev

    - name: Install ALSA dev
      run: sudo apt-get install libasound2-dev

    - name: Install PulseAudio dev
      run: sudo apt-get install libpulse-dev

    - name: Install Python dev
      run: sudo apt-get install python3.7-dev

    - name: Build DJV
      run: >
        mkdir build &&
        cd build &&
        export DJV_BUILD=$PWD &&
        export PATH=$PATH:$DJV_BUILD/install/bin &&
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DJV_BUILD/install/lib &&
        export PYTHONPATH=$DJV_BUILD/install/lib:$PYTHONPATH &&
        mkdir SuperBuild &&
        cd SuperBuild &&
        cmake ../.. -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX=$DJV_BUILD/install -DCMAKE_PREFIX_PATH=$DJV_BUILD/install -DDJV_THIRD_PARTY_OPTIONAL=FALSE -DDJV_BUILD_TINY=TRUE -DDJV_GCOV=TRUE -DDJV_PYTHON=FALSE -DDJV_GL_ES2=TRUE &&
        cmake --build . -j 4

    - name: Run tests
      run: >
        cd build &&
        export DJV_BUILD=$PWD &&
        export PATH=$PATH:$DJV_BUILD/install/bin &&
        export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$DJV_BUILD/install/lib &&
        export PYTHONPATH=$DJV_BUILD/install/lib:$PYTHONPATH &&
        cd SuperBuild/DJV/src/DJV-build &&
        cmake --build . --target test &&
        cat Testing/Temporary/LastTest.log
